### ISSUE TITLE
3 instances of each sonos device

### ISSUE THREAD

**Issue by webtrend** [stephen/airsonos#185]
I just installedon the server on ubuntu 14.04. It works beautifully!

However, when I start the server, it finds 3 instances of the same device on the network (same IP address for each device). As a result, I see 9 devices on my airplay instead of 3. 

Any idea on how to resolve this?

**Comment by idallas** [comment]
This is happening to me, too.  I have 7 Sonos zones/players on my network and when launching airsonos  it finds 7 instances of each for a total of 49.  My sound output airplay choices shows more than 7 of each, most showing 14 copies and a couple showing only 12 or 13 (which doesn't make sense to me).

**Comment by idallas** [comment]
Note: this is a dupe of https://github.com/stephen/airsonos/issues/114

**Comment by idallas** [comment]
Fixed by https://github.com/stephen/node-sonos/pull/1

**Comment by piamliam** [comment]
How do I implement this fix? I have tried to reinstall airsonos and still no luck. This is what happens. 
<img width="571" alt="screen shot 2015-07-11 at 20 05 47" src="https://cloud.githubusercontent.com/assets/13292036/8635006/e7d3f7a8-2808-11e5-8b97-6a6d5df9ed56.png">

**Comment by kujohn** [comment]
I am experiencing this as well.
@piamliam doesn't look like that PR was merged and used/released for airsonos on npm

You'll have to manually clone airsonos and use the PR author's [repo](https://github.com/lirenzhu/airsonos/tree/with-node-sonos-fix) in `node_modules`

**Comment by piamliam** [comment]
Hi john

do you have steps on how to do this?

Im not very good with this stuff

Thanks

**Comment by webtrend** [comment]
@piamliam 

You just have to follow the link and download logicalDevice.js file. Replace that file on your system. The installation folder probably varies according to the OS. In my case (Ubuntu 14.04), the install folder was /usr/local/lib/node_modules/sonos/lib

Once you replace the file, you can restart the airsonos service. Problem solved.

**Comment by mihalski** [comment]
Does anyone have any idea how to install https://github.com/lirenzhu/airsonos/tree/with-node-sonos-fix ? I've been trying for hours with no luck.. I just keep having the exact same problem with multiple copies of each device.

**Comment by lirenzhu** [comment]
@mihalski and anyone who's interested:
1. Download it as a zip (https://github.com/lirenzhu/airsonos/archive/with-node-sonos-fix.zip)
2. Unzip the project
3. Use console to run `npm install` in the unzipped project directory
4. `node index.js`

**Comment by mihalski** [comment]
Thank you.

Sorry, I've been away for a week. I thought I had tried exactly that but when I did it just now it worked. Thank you!

But this brings me to the second problem.. I've never actually been able to get it to work in terms of audio being sent to the Sonos devices. The Airplay selection just instantly disappears, playback pauses and then the Airplay option for the device re-appears.

Here's the results of --verbose for two subsequent attempt to play some audio from my iPhone 6:

    macmini:airsonos-with-node-sonos-fix michal$ node index.js --verbose
    Searching for Sonos devices on network...
    Setting up AirSonos for Family Room {192.168.1.158:1400}
      nodetunes:server starting nodetunes server (Family Room (AirSonos)) +0ms
      nodetunes:server broadcasting mdns advertisement (for port 5000) +21ms
    Setting up AirSonos for Patio {192.168.1.108:1400}
      nodetunes:server starting nodetunes server (Patio (AirSonos)) +5ms
      nodetunes:server broadcasting mdns advertisement (for port 5001) +10ms
    Setting up AirSonos for Stan's Bedroom {192.168.1.176:1400}
      nodetunes:server starting nodetunes server (Stan's Bedroom (AirSonos)) +7ms
      nodetunes:server broadcasting mdns advertisement (for port 5002) +26ms
    Setting up AirSonos for Living Room {192.168.1.55:1400}
      nodetunes:server starting nodetunes server (Living Room (AirSonos)) +2ms
      nodetunes:server broadcasting mdns advertisement (for port 5003) +9ms
      nodetunes:rtsp received method OPTIONS (CSeq: 0)
    { cseq: '0',
      'x-apple-device-id': '0xd4f46f0ee186',
      'apple-challenge': 'hhcNr2Mz7RCaI71eE64z4w==',
      'dacp-id': '6367BF9A71CBBD21',
      'active-remote': '2269815748',
      'user-agent': 'AirPlay/220.68',
      'content-length': '0' } +10s
      nodetunes:helper building challenge for hhcNr2Mz7RCaI71eE64z4w== (ip: c0a80105, mac: 545200631be4) +2ms
      nodetunes:helper computed challenge: KaIW9PT2OdmW8hm//BG8ATHnlo2Y7nkxQHvHHlmO2jfB+wSvJJjby2VaUuIgrDPxIiMl8ritCaQq6cAupC1Xh/hANhKrBVo3tLSffu14j6UVhLgbBTCfvawDRhOje6XUDvrfWfmr1P0uOAhqYhrwJaBpNmYppVF3Oxa6n+JYBJuT6+nRsI7swJkbknvqbcc5TTy37zvYK2gDvi/G8uTDlDT1QJ/XF92xA0AGkN1acXiaajIFjdOnzwaVahFuGQxFY5YKScpqtjDU8J/VC0LzJwxupyL4xtOspDgy/m4lEyPgjz3WZRgwtNQq/pPMAdIunIh4px26TuQNcNvmy3vLVg== +123ms
      nodetunes:rtsp received method OPTIONS (CSeq: 0)
    { cseq: '0',
      'x-apple-device-id': '0xd4f46f0ee186',
      'apple-challenge': 'kqOi1Q7NBq0khwIheoSrGw==',
      'dacp-id': '6367BF9A71CBBD21',
      'active-remote': '911081038',
      'user-agent': 'AirPlay/220.68',
      'content-length': '0' } +9s
      nodetunes:helper building challenge for kqOi1Q7NBq0khwIheoSrGw== (ip: c0a80105, mac: 545200631be4) +1ms
      nodetunes:helper computed challenge: lTRZ0HFyoKYiOB8VWlGAhV2uRf9XZ/URkbW03DCCs/5TVX7k23XZE0WjrI1aSRqwWBJOzGFYI1OBpubH1u7Ejw5zme/iynNcrhfg0y1wDeFRH1q4DiQ8xNJ1PKVXUaHcJsBzOOi7GZCLSajOJLX3UyxBBqFsbyzbpy6Zv+9emlUuAAdx9oBeA+0S9AghFgTEal/Q9d9qeRMgCNm52c/mx5z0lHbFZFK3JtUcgIVMX2K8mV2aKYmDeNqv7Q2acWrXDRANmaCK7Ozv3I9LWJiKvSYhIWw5gFZhgmHolElTkQmHj6X62yR++o8XTHEoVc+TG2TZY4D8jVmmpI95BNEkZA== +86ms

Does that help identify any potential problems I need to resolve?

Again, thank you for your help!

Regards,
Michal

**Comment by lirenzhu** [comment]
@mihalski this sounds like your issue: https://github.com/stephen/airsonos/issues/80#issuecomment-127040749

**Comment by mihalski** [comment]
Thank you so much! That DID fix my problem.

It's unusual that the default for ipv6 seems to be set to "automatically" without "off" even being an option in the gui. The only way to disable ipv6 completely seems to be networksetup, so I did so for wi-fi and ethernet.

How is it that this does not affect everyone trying airsonos?

Thank you very much.

Regards,
Michal

P.S. I presume it is expected that there is a significant delay in the audio between the iOS device and the Sonos speakers when using airsonos?

**Comment by lirenzhu** [comment]
@mihalski IPv6 configurations exist under System Preferences -> Network -> (select the interface you use) -> Advanced -> TCP/IP -> Configure IPv6. You can set it to 'Off' there, at least it's available for me on OS X Yosemite. 

Not sure why it doesn't affect everyone, the option is set to off by default for me. But I run airsonos on a Raspberry Pi instead of my computer. And yes there is a fair amount of delay in my experience, maybe 3-5 seconds (my really rough estimate).

**Comment by mihalski** [comment]
Interesting.

I have 3 different installations of Yosemite (all latest update) and none of them have "Off" as an option in the GUI until AFTER I run networksetup. Only the 3 other options were available and "Automatic" was the default.

I had that preference pane open when I made the changes from the command line and in each case "Off" just magically appeared as the current setting.

**Comment by aaranedac** [comment]
@lirenzhu I got this when I tried to apply your fix:
ANDRESs-MacBook-Pro:airsonos-with-node-sonos-fix andresaraneda$ node index.js

module.js:340
    throw err;
          ^
Error: Cannot find module '../build/Release/dns_sd_bindings'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/andresaraneda/Downloads/airsonos-with-node-sonos-fix/node_modules/nodetunes/node_modules/mdns/lib/dns_sd.js:32:22)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

**Comment by lirenzhu** [comment]
@aaranedac take a look at the original [INSTALL.md](https://github.com/stephen/airsonos/blob/master/INSTALL.md), make sure your environment has all the necessary dependencies. I suspect if you're on a linux distro that you're missing libavahi-compat-libdnssd-dev

**Comment by aaranedac** [comment]
@lirenzhu I'm on MAC OSX 10.10.4 it should work but it didn`t.
